version: '3.1'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/application
            - ./phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - scoroht-network
    php:
        image: php:8.0.9-fpm
        volumes:
            - .:/application
        networks:
            - scoroht-network
    composer:
        restart: 'no'
        image: composer/composer:latest
        command: composer install
        volumes:
            - .:/app
networks:
    scoroht-network:
        driver: bridge